# Generated by Django 2.2.6 on 2019-11-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sell', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(max_length=600)),
                ('available', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('image1', models.FileField(blank=True, null=True, upload_to='product_pics')),
                ('image2', models.FileField(blank=True, null=True, upload_to='product_pics')),
                ('image3', models.FileField(blank=True, null=True, upload_to='product_pics')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-create_at',),
            },
        ),
    ]
