# Generated by Django 2.2.6 on 2019-11-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
